PathWeaver project configuration: Wheelbase or Track
wpilibsuite/PathWeaver pull request #249
Opened 2021-04-07 00:08 UTC by jasondaming

Closes #247

2021-04-11 22:55 UTC, AustinShalit requested changes

2021-04-11 22:55 UTC, AustinShalit commented on src/main/java/edu/wpi/first/pathweaver/ProjectPreferences.java
> +		private final double trackWidth;
This breaks save file backwards compatibility. We need to "upgrade" user save files.

2021-04-12 04:14 UTC, jasondaming commented
This allows loading from either trackWidth or wheelBase!

2021-04-16 01:39 UTC, AustinShalit approved these changes

2021-04-16 01:52 UTC, merged